// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCe8N8en4tVoXE0bq7_8M39ipus4x7DG7w',
    appId: '1:924722694431:web:c3b3b747c939965075082a',
    messagingSenderId: '924722694431',
    projectId: 'connect-81717',
    authDomain: 'connect-81717.firebaseapp.com',
    storageBucket: 'connect-81717.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGxBmp5FHZ_huGlVmsuNx0kyhSQCCjQ7k',
    appId: '1:924722694431:android:b1f9df953f37353575082a',
    messagingSenderId: '924722694431',
    projectId: 'connect-81717',
    storageBucket: 'connect-81717.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6Cf8SZAVQqQO9WXa-kQ1XoGFWB4jvhPk',
    appId: '1:924722694431:ios:22b216943c0ae22575082a',
    messagingSenderId: '924722694431',
    projectId: 'connect-81717',
    storageBucket: 'connect-81717.appspot.com',
    iosClientId: '924722694431-7dt44o24jgikdejpgcanfofuu6jt6r1v.apps.googleusercontent.com',
    iosBundleId: 'com.example.agni',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6Cf8SZAVQqQO9WXa-kQ1XoGFWB4jvhPk',
    appId: '1:924722694431:ios:22b216943c0ae22575082a',
    messagingSenderId: '924722694431',
    projectId: 'connect-81717',
    storageBucket: 'connect-81717.appspot.com',
    iosClientId: '924722694431-7dt44o24jgikdejpgcanfofuu6jt6r1v.apps.googleusercontent.com',
    iosBundleId: 'com.example.agni',
  );
}
